services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    restart: always
    ports:
      - '${REDIS_PORT}:6379'

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - '${API_PORT}:3009'
    environment:
      - PORT=${API_PORT}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      - postgres
      - redis

  # 3. 프론트엔드 (Next.js)
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_WEBSOCKET_URL: ${NEXT_PUBLIC_WEBSOCKET_URL}
    ports:
      - '${WEB_PORT}:3010'
    environment:
      - PORT=${WEB_PORT}
      - BUILD_ENV=docker
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_WEBSOCKET_URL=${NEXT_PUBLIC_WEBSOCKET_URL}
    depends_on:
      - api

  nginx:
    image: nginx:latest
    ports:
      - '80:80' # 브라우저는 이제 80번으로 접속합니다!
    volumes:
      # 아까 만든 설정 파일을 컨테이너 안으로 집어넣기
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api # 백엔드가 켜져야 Nginx도 켬
      - web # 프론트가 켜져야 Nginx도 켬
volumes:
  postgres_data:
